name: Première CI

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
  

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Installation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installation des dépendances
        run: npm install

      - name: Lint du code
        run: npm run lint

        # Scan de vulnérabilités SCA
      - name: SCA - Audit des dépendances
        run: npm audit --audit-level=high

        # Scan de failles du code SAST
      - name: SAST - Scan du code source (Semgrep)
        uses: semgrep/semgrep-action@v1
        with:
          config: p/javascript

      - name: Tests
        run: npm run test

      #Notification discord
      - name: Notify d'échec (Discord)
        if: failure()
        run: |
          echo "### ❌ Échec de la Pipeline de Sécurité" >> $GITHUB_STEP_SUMMARY
          echo "Une vulnérabilité ou un bug a été détecté. Vérifiez les logs SAST/SCA." >> $GITHUB_STEP_SUMMARY
 
          # Envoi d'un Webhook Discord
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "username": "CI/CD Bot",
            "embeds": [{
              "title": "❌ Pipeline échouée : ça marche pas"
            }]
          }' \
          ${{ secrets.DISCORD_WEBHOOK }}
          
  deploy:
    runs-on: ubuntu-latest  

    steps:
      - uses: ttskch/render-deploy@v1.0.0
        with:
          # On utilise maintenant le Secret pour la sécurité
          api-key: ${{ secrets.RENDER_API_KEY }}
          service-id: srv-d69ds53uibrs739eiu0g
 