name: Première CI

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
  

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Installation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installation des dépendances
        run: npm install

      - name: Lint du code
        run: npm run lint

        # Scan de vulnérabilités SCA
      - name: SCA - Audit des dépendances
        run: npm audit --audit-level=high

        # Scan de failles du code SAST
      - name: SAST - Scan du code source (Semgrep)
        uses: semgrep/semgrep-action@v1
        with:
          config: p/javascript

      - name: Tests
        run: npm run test

        # Notifier sur discord      
      - name: Notify Discord (Failure)
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"content":"❌ Pipeline FAILED ! Vérifiez les vulnérabilités."}' \
          ${{ secrets.DISCORD_WEBHOOK }}
  
  deploy:
    runs-on: ubuntu-latest  

    steps:
      - uses: ttskch/render-deploy@v1.0.0
        with:
          # On utilise maintenant le Secret pour la sécurité
          api-key: ${{ secrets.RENDER_API_KEY }}
          service-id: srv-d69ds53uibrs739eiu0g
 